### ISSUE TITLE
Return Blank Camera View On ios

### ISSUE THREAD

**Issue by madypamungkas** [nusanet/flutter-native-screenshot#4]
Berjalan normal di android, camera preview dapat terscreenshoot dengan baik, namun blank view saat dijalankan di ios,
![WhatsApp Image 2021-12-29 at 08 27 08](https://user-images.githubusercontent.com/39006120/147618938-8bf2816f-cf1c-4749-bb1a-4bfc091bf2c2.jpeg)

**Comment by CoderJava** [comment]
Permission di iOS sudah disetup?
![Screen Shot 2021-12-29 at 08 40 54](https://user-images.githubusercontent.com/17062085/147619515-60607848-bab1-48bf-a8b7-bd120abc1143.png)

**Comment by madypamungkas** [comment]
sudah, sudah berhasil menyimpan juga, tapi saat screenshoot camera(scan qr) preview return blank
![image](https://user-images.githubusercontent.com/39006120/147619574-01c260a3-ae65-4780-ae25-f84995dd5829.png)

**Comment by erdoganerhan** [comment]
I have same problem.When I use Platform Views. (Example: Google Maps, Camera etc)

info.plist
` <key>NSPhotoLibraryAddUsageDescription</key>`
`<string>This app requires access to the photo library.</string>`

**Comment by CoderJava** [comment]
> Berjalan normal di android, camera preview dapat terscreenshoot dengan baik, namun blank view saat dijalankan di ios, ![WhatsApp Image 2021-12-29 at 08 27 08](https://user-images.githubusercontent.com/39006120/147618938-8bf2816f-cf1c-4749-bb1a-4bfc091bf2c2.jpeg)

Ini saya coba reproduce camera preview dan google maps di iOS. Tapi, nggak ketemu bug-nya nih.

https://user-images.githubusercontent.com/17062085/147799428-9254e4c6-a2cf-4a61-85dc-cac8ec0b8df5.mp4

Ini saya pakai plugin [camera](https://pub.dev/packages/camera) punya-nya si Flutter aman-aman saja. Mungkin bisa diberitahu info plugin camera yang digunakan apa ya?

**Comment by CoderJava** [comment]
> I have same problem.When I use Platform Views. (Example: Google Maps, Camera etc)
> 
> info.plist ` <key>NSPhotoLibraryAddUsageDescription</key>` `<string>This app requires access to the photo library.</string>`

This plugin not used Platform Views. It is using native code to take the screenshot. And it's working to take screenshot Google Maps and camera.

https://user-images.githubusercontent.com/17062085/147799496-896b4d57-fb9d-4709-a768-1dce0e9201f7.mp4

**Comment by madypamungkas** [comment]
kasus yang saya temui, saya menggunakan plugin qr_code_scanner (https://pub.dev/packages/qr_code_scanner). coba saya reproduce menggunakan plugin lain, untuk memastikan plugin flutter-native-screenshot berjalan dengan baik. Terimakasih

**Comment by zafranf** [comment]
> kasus yang saya temui, saya menggunakan plugin qr_code_scanner (https://pub.dev/packages/qr_code_scanner). coba saya reproduce menggunakan plugin lain, untuk memastikan plugin flutter-native-screenshot berjalan dengan baik. Terimakasih

up, sama nih kasusnya, pake qr_code_scanner klo di ios cuma muncul bingkainya aja gak sama preview kameranya..
