### ISSUE TITLE
bug--ios ，video screenshot

### ISSUE THREAD

**Issue by devyueyue** [nusanet/flutter-native-screenshot#5]
IOS, the video screenshot is invalid, and the content of the video is not intercepted

**Comment by CoderJava** [comment]
@devyueyue Can you give some informations such as flutter version, os version, and how to reproduce it.

**Comment by devyueyue** [comment]
https://pub.dev/packages/better_player
使用这个播放器，ios手机截图无效，获取不到截图的图片
