### ISSUE TITLE
Add support for Android 13

### ISSUE THREAD

**Issue by jepino** [nusanet/flutter-native-screenshot#7]
I get this warning when building for android:  
`flutter_native_screenshot-1.1.2/android/src/main/java/net/bengkelrobot/flutter_native_screenshot/FlutterNativeScreenshotPlugin.java uses or overrides a deprecated API`

**Comment by K123Ritesh** [comment]
@jepino  issue resolved??

**Comment by jepino** [comment]
@K123Ritesh  This plugin doesn't seem to be maintained anymore. I ended up removing it and writing the screenshot logic myself using `RenderRepaintBoundary.toImage`.

**Comment by K123Ritesh** [comment]
@jepino  Yep, you're right i also implemented it natively at the end . btw thanks
