### ISSUE TITLE
It doesn't recognize the package after the package is installed

### ISSUE THREAD

**Issue by jdevp** [nusanet/flutter-native-screenshot#8]
Hi,

The package is not recognized after the installation.

import 'package:flutter_native_screenshot/flutter_native_screenshot.dart';

Target of URI doesn't exist

**Comment by CoderJava** [comment]
I already tested it and it's working. Try run `flutter pub get` again.
![Screen Shot 2023-06-23 at 13 49 01](https://github.com/nusanet/flutter-native-screenshot/assets/17062085/c3bdff01-a39a-4bee-9221-7c0c2996aea4)
